FILE "CD [TopGun Disc 2].bin" BINARY

REM ORIGINAL MEDIA-TYPE: CD

  REM SESSION 01        (*)
    TRACK 01 CDI/2352
      INDEX 01 00:00:00
         REM LBA: 0

REM (*) SESSION commands are not supported by all applications

REM Generated by IsoBuster 4.7.0.00 (https://www.isobuster.com)
