FILE "fmvdemo.bin" BINARY

REM ORIGINAL MEDIA-TYPE: CD

  REM SESSION 01        ; Not supported by other applications (*)
    TRACK 01 MODE1/2352
      INDEX 01 00:00:00
      REM MSF: 00:00:00 = LBA: 0

REM (*) SESSION directives are unfortunately not properly supported
REM     'out there'.  IsoBuster however supports them !

REM Generated by IsoBuster 4.1.0.00 (https://www.isobuster.com)
